version: '3.8'

services:
  app:
    build: .
    container_name: fastapi-project-app
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - NEWS_API_KEY=${NEWS_API_KEY}
      - NEWS_API_URL=${NEWS_API_URL}
      - DATABASE_URL=${DATABASE_URL_DOCKER}
      - SECRET_KEY=${SECRET_KEY}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - DEBUG=${DEBUG:-false}
    volumes:
      - ./app.log:/app/app.log
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  db:
    image: postgres:13
    container_name: fastapi-project-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: news
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d news"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres_data: